### ISSUE TITLE
[ubuntu22.04][jax==0.4.26] Installation Failed: conda env create --file=environment.yml

### ISSUE THREAD

**Issue by fangkun1990** [google-research/timesfm#53]
The conflict is caused by:
    praxis 1.4.0 depends on tfds-nightly==4.8.3.dev202303280045
    The user requested jax==0.4.26
    jax[cuda12] 0.4.26 depends on jax 0.4.26 (from https://pypi.tuna.tsinghua.edu.cn/packages/dc/d9/f387d9dfb2cf00f814b24e0f8bf6f4c68ae01870994dc436993fadd73563/jax-0.4.26-py3-none-any.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/jax/) (requires-python:>=3.9))
    praxis 1.3.1 depends on jax==0.4.24
    The user requested jax==0.4.26
    jax[cuda12] 0.4.26 depends on jax 0.4.26 (from https://pypi.tuna.tsinghua.edu.cn/packages/dc/d9/f387d9dfb2cf00f814b24e0f8bf6f4c68ae01870994dc436993fadd73563/jax-0.4.26-py3-none-any.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/jax/) (requires-python:>=3.9))
    praxis 1.3.0 depends on jax==0.4.24
    The user requested jax==0.4.26
    jax[cuda12] 0.4.26 depends on jax 0.4.26 (from https://pypi.tuna.tsinghua.edu.cn/packages/dc/d9/f387d9dfb2cf00f814b24e0f8bf6f4c68ae01870994dc436993fadd73563/jax-0.4.26-py3-none-any.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/jax/) (requires-python:>=3.9))
    praxis 1.2.0 depends on jax==0.4.18
    The user requested jax==0.4.26
    jax[cuda12] 0.4.26 depends on jax 0.4.26 (from https://pypi.tuna.tsinghua.edu.cn/packages/dc/d9/f387d9dfb2cf00f814b24e0f8bf6f4c68ae01870994dc436993fadd73563/jax-0.4.26-py3-none-any.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/jax/) (requires-python:>=3.9))
    praxis 1.1.0 depends on jax==0.4.14
    The user requested jax==0.4.26
    jax[cuda12] 0.4.26 depends on jax 0.4.26 (from https://pypi.tuna.tsinghua.edu.cn/packages/dc/d9/f387d9dfb2cf00f814b24e0f8bf6f4c68ae01870994dc436993fadd73563/jax-0.4.26-py3-none-any.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/jax/) (requires-python:>=3.9))
    praxis 1.0.0 depends on jax==0.4.7
    praxis 0.3.0 depends on t5x
    praxis 0.2.1 depends on t5x
    praxis 0.2.0 depends on t5x
    praxis 0.1 depends on t5x

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

Pip subprocess error:
ERROR: Cannot install -r /home/timesfm-master/condaenv.4cyxofwn.requirements.txt (line 3), jax==0.4.26 and jax[cuda12]==0.4.26 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

failed

CondaEnvException: Pip failed

**Comment by yfprime** [comment]
I've been having the same issue. And if you install the latest jax package with conda, you get this:

`Traceback (most recent call last):                                                                                                                                                                                                                                                                                           
  File "/home/main/tf1/src/trainer1.py", line 1, in <module>                                                                                                                                                                                                                                                                 
    import timesfm                                                                                                                                                                                                                                                                                                           
  File "/home/main/tf1/src/timesfm.py", line 29, in <module>                                                                                                                                                                                                                                                                 
    from paxml import checkpoints                                                                                                                                                                                                                                                                                            
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/paxml/checkpoints.py", line 30, in <module>                                                                                                                                                                                                           
    import optax 
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/optax/__init__.py", line 17, in <module> 
    from optax import contrib 
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/optax/contrib/__init__.py", line 21, in <module> 
    from optax.contrib._dadapt_adamw import dadapt_adamw 
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/optax/contrib/_dadapt_adamw.py", line 27, in <module> 
    from optax._src import utils 
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/optax/_src/utils.py", line 25, in <module> 
    import jax.scipy.stats.norm as multivariate_normal 
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/jax/scipy/stats/__init__.py", line 40, in <module> 
    from jax._src.scipy.stats.kde import gaussian_kde as gaussian_kde 
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/jax/_src/scipy/stats/kde.py", line 26, in <module> 
    from jax.scipy import linalg, special 
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/jax/scipy/linalg.py", line 18, in <module> 
    from jax._src.scipy.linalg import ( 
  File "/home/main/anaconda3/envs/tfm_env/lib/python3.10/site-packages/jax/_src/scipy/linalg.py", line 403, in <module> 
    @_wraps(scipy.linalg.tril) 
AttributeError: module 'scipy.linalg' has no attribute 'tril' 
`

**Comment by oops343** [comment]
same here

**Comment by fangkun1990** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我暂时无法亲自回复您的邮件。我会尽快和您取得联系。
