### ISSUE TITLE
circular import

### ISSUE THREAD

**Issue by UP61** [google-research/timesfm#54]
(tfm_env) root@debian:~/timesfm# python timesfm.py
Traceback (most recent call last):
  File "/root/timesfm/timesfm.py", line 7, in <module>
    from timesfm import TimesFm
  File "/root/timesfm/timesfm.py", line 7, in <module>
    from timesfm import TimesFm
ImportError: cannot import name 'TimesFm' from partially initialized module 'timesfm' (most likely due to a circular import) (/root/timesfm/timesfm.py)

---------------------------------------------------
Iuse this code:        https://github.com/lhw828/timesfm/blob/main/timesfm.py

**Comment by ismailsimsek** [comment]
Pinning jax and jaxlib to same version solved it for me

```
jax==0.4.28
jaxlib==0.4.28
```
https://github.com/google/jax/discussions/14036#discussioncomment-4710051
